/*
Restricciones principales:
- `PRIMARY KEY` para identificar cada registro.
- `FOREIGN KEY` para mantener las relaciones.
- `NOT NULL` para atributos obligatorios.
- `UNIQUE` para correos y documentos no repetidos.
- `CHECK` para validar `alta`, montos, plazos, tasas y documentos.
- `DEFAULT` para fechas, estados iniciales y registros activos.
- `timestamptz` para fechas y horas, usando `YYYY-MM-DD HH:MM:SS` como formato de intercambio.
- `ON DELETE RESTRICT` para evitar borrar registros relacionados.
- `ON UPDATE RESTRICT` para impedir cambios accidentales de identificadores referenciados.
*/


SET TIME ZONE 'America/Lima';
/*
Creacion de trablas
*/
CREATE EXTENSION IF NOT EXISTS citext;

CREATE TYPE estado_aliado AS ENUM ('pendiente', 'activo', 'inactivo');
CREATE TYPE estado_producto AS ENUM ('borrador', 'activo', 'inactivo');
CREATE TYPE estado_campana AS ENUM ('borrador', 'activa', 'finalizada', 'cancelada');
CREATE TYPE tipo_documento AS ENUM ('DNI', 'CE', 'PASAPORTE', 'RUC');
CREATE TYPE tipo_persona AS ENUM ('NATURAL', 'JURIDICA');
CREATE TYPE tipo_tasa_interes AS ENUM ('TEA', 'TNA');
CREATE TYPE resultado_precalificacion AS ENUM ('pendiente', 'precalificado', 'no_precalificado');
CREATE TYPE estado_solicitud AS ENUM ('precalificado', 'no_precalificado', 'derivado', 'en_evaluacion', 'aprobado', 'rechazado', 'cerrado', 'cancelado');

CREATE TABLE rol (
	id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	nombre_rol varchar(30) NOT NULL UNIQUE,
	alta smallint NOT NULL DEFAULT 1 CHECK (alta IN (0, 1)),
	creado_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE aliado (
	id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	razon_social varchar(150) NOT NULL,
	tipo_documento tipo_documento NOT NULL DEFAULT 'RUC',
	numero_documento varchar(15) NOT NULL UNIQUE,
	contacto_nombre varchar(120) NOT NULL,
	contacto_correo citext NOT NULL,
	contacto_telefono varchar(15),
	estado estado_aliado NOT NULL DEFAULT 'pendiente',
	alta smallint NOT NULL DEFAULT 1 CHECK (alta IN (0, 1)),
	creado_at timestamptz NOT NULL DEFAULT now(),
	actualizado_at timestamptz NOT NULL DEFAULT now(),
	CHECK (tipo_documento = 'RUC' AND numero_documento ~ '^[0-9]{11}$')
);

CREATE TABLE usuario (
	id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	rol_id integer NOT NULL REFERENCES rol(id) ON DELETE RESTRICT,
	aliado_id integer REFERENCES aliado(id) ON DELETE RESTRICT,
	correo_electronico citext NOT NULL UNIQUE,
	password_hash text NOT NULL,
	activo boolean NOT NULL DEFAULT true,
	alta smallint NOT NULL DEFAULT 1 CHECK (alta IN (0, 1)),
	ultimo_acceso_at timestamptz,
	creado_at timestamptz NOT NULL DEFAULT now(),
	actualizado_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE categoria (
	id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	nombre varchar(80) NOT NULL UNIQUE,
	descripcion text,
	activo boolean NOT NULL DEFAULT true,
	alta smallint NOT NULL DEFAULT 1 CHECK (alta IN (0, 1))
);

CREATE TABLE producto (
	id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	aliado_id integer NOT NULL REFERENCES aliado(id) ON DELETE RESTRICT,
	categoria_id integer REFERENCES categoria(id) ON DELETE RESTRICT,
	nombre varchar(160) NOT NULL,
	descripcion text,
	precio_lista numeric(14, 2) CHECK (precio_lista IS NULL OR precio_lista >= 0),
	moneda varchar(3) NOT NULL DEFAULT 'PEN',
	incluye_igv boolean NOT NULL DEFAULT true,
	imagen_url text,
	estado estado_producto NOT NULL DEFAULT 'borrador',
	alta smallint NOT NULL DEFAULT 1 CHECK (alta IN (0, 1)),
	creado_at timestamptz NOT NULL DEFAULT now(),
	actualizado_at timestamptz NOT NULL DEFAULT now(),
	CHECK (moneda = 'PEN')
);

CREATE TABLE tipo_financiamiento (
	id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	codigo varchar(30) NOT NULL UNIQUE,
	nombre varchar(100) NOT NULL UNIQUE,
	descripcion text,
	activo boolean NOT NULL DEFAULT true,
	alta smallint NOT NULL DEFAULT 1 CHECK (alta IN (0, 1))
);

CREATE TABLE producto_financiamiento (
	id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	producto_id integer NOT NULL REFERENCES producto(id) ON DELETE RESTRICT,
	tipo_financiamiento_id integer NOT NULL REFERENCES tipo_financiamiento(id) ON DELETE RESTRICT,
	tipo_tasa tipo_tasa_interes NOT NULL,
	tasa_anual numeric(7, 4) NOT NULL CHECK (tasa_anual BETWEEN 0 AND 100),
	plazo_minimo_meses smallint NOT NULL CHECK (plazo_minimo_meses > 0),
	plazo_maximo_meses smallint NOT NULL CHECK (plazo_maximo_meses >= plazo_minimo_meses),
	monto_minimo numeric(14, 2) CHECK (monto_minimo IS NULL OR monto_minimo >= 0),
	monto_maximo numeric(14, 2) CHECK (monto_maximo IS NULL OR monto_maximo >= monto_minimo),
	vigente_desde timestamptz NOT NULL,
	vigente_hasta timestamptz,
	activo boolean NOT NULL DEFAULT true,
	alta smallint NOT NULL DEFAULT 1 CHECK (alta IN (0, 1)),
	UNIQUE (producto_id, tipo_financiamiento_id, vigente_desde),
	UNIQUE (id, producto_id),
	CHECK (vigente_hasta IS NULL OR vigente_hasta >= vigente_desde)
);

CREATE TABLE campana (
	id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	nombre varchar(150) NOT NULL,
	descripcion text,
	fecha_inicio timestamptz NOT NULL,
	fecha_fin timestamptz NOT NULL,
	estado estado_campana NOT NULL DEFAULT 'borrador',
	creado_por_id integer NOT NULL REFERENCES usuario(id) ON DELETE RESTRICT,
	alta smallint NOT NULL DEFAULT 1 CHECK (alta IN (0, 1)),
	creado_at timestamptz NOT NULL DEFAULT now(),
	CHECK (fecha_fin >= fecha_inicio)
);

CREATE TABLE campana_producto (
	campana_id integer NOT NULL REFERENCES campana(id) ON DELETE RESTRICT,
	producto_id integer NOT NULL REFERENCES producto(id) ON DELETE RESTRICT,
	beneficio text,
	condiciones_comerciales text,
	alta smallint NOT NULL DEFAULT 1 CHECK (alta IN (0, 1)),
	PRIMARY KEY (campana_id, producto_id)
);

CREATE TABLE regla_precalificacion (
	id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	campana_id integer NOT NULL REFERENCES campana(id) ON DELETE RESTRICT,
	edad_minima smallint CHECK (edad_minima IS NULL OR edad_minima >= 18),
	edad_maxima smallint CHECK (edad_maxima IS NULL OR edad_maxima >= edad_minima),
	ingreso_mensual_minimo numeric(14, 2) CHECK (ingreso_mensual_minimo IS NULL OR ingreso_mensual_minimo >= 0),
	monto_minimo numeric(14, 2) CHECK (monto_minimo IS NULL OR monto_minimo >= 0),
	monto_maximo numeric(14, 2) CHECK (monto_maximo IS NULL OR monto_maximo >= monto_minimo),
	plazo_meses_minimo smallint CHECK (plazo_meses_minimo IS NULL OR plazo_meses_minimo > 0),
	plazo_meses_maximo smallint CHECK (plazo_meses_maximo IS NULL OR plazo_meses_maximo >= plazo_meses_minimo),
	activo boolean NOT NULL DEFAULT true,
	alta smallint NOT NULL DEFAULT 1 CHECK (alta IN (0, 1))
);

CREATE TABLE cliente (
	id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	tipo_persona tipo_persona NOT NULL,
	tipo_documento tipo_documento NOT NULL,
	numero_documento varchar(15) NOT NULL,
	nombres varchar(100),
	apellidos varchar(100),
	razon_social varchar(150),
	correo_electronico citext NOT NULL,
	telefono varchar(15),
	fecha_nacimiento timestamptz,
	alta smallint NOT NULL DEFAULT 1 CHECK (alta IN (0, 1)),
	creado_at timestamptz NOT NULL DEFAULT now(),
	actualizado_at timestamptz NOT NULL DEFAULT now(),
	UNIQUE (tipo_documento, numero_documento),
	CHECK (
		(tipo_persona = 'NATURAL' AND tipo_documento IN ('DNI', 'CE', 'PASAPORTE')
		 AND nombres IS NOT NULL AND apellidos IS NOT NULL AND razon_social IS NULL)
		OR
		(tipo_persona = 'JURIDICA' AND tipo_documento = 'RUC'
		 AND numero_documento ~ '^[0-9]{11}$' AND razon_social IS NOT NULL
		 AND nombres IS NULL AND apellidos IS NULL)
	)
);

CREATE TABLE lista_interes (
	id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	cliente_id integer NOT NULL REFERENCES cliente(id) ON DELETE RESTRICT,
	producto_id integer NOT NULL REFERENCES producto(id) ON DELETE RESTRICT,
	creado_at timestamptz NOT NULL DEFAULT now(),
	alta smallint NOT NULL DEFAULT 1 CHECK (alta IN (0, 1)),
	UNIQUE (cliente_id, producto_id)
);

CREATE TABLE solicitud_financiamiento (
	id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	cliente_id integer NOT NULL REFERENCES cliente(id) ON DELETE RESTRICT,
	producto_id integer NOT NULL REFERENCES producto(id) ON DELETE RESTRICT,
	producto_financiamiento_id integer NOT NULL,
	campana_id integer REFERENCES campana(id) ON DELETE RESTRICT,
	monto_solicitado numeric(14, 2) NOT NULL CHECK (monto_solicitado > 0),
	moneda varchar(3) NOT NULL DEFAULT 'PEN' CHECK (moneda = 'PEN'),
	plazo_meses smallint NOT NULL CHECK (plazo_meses > 0),
	tasa_tipo_aplicada tipo_tasa_interes NOT NULL,
	tasa_anual_aplicada numeric(7, 4) NOT NULL CHECK (tasa_anual_aplicada BETWEEN 0 AND 100),
	resultado_precalificacion resultado_precalificacion NOT NULL DEFAULT 'pendiente',
	estado estado_solicitud NOT NULL DEFAULT 'precalificado',
	alta smallint NOT NULL DEFAULT 1 CHECK (alta IN (0, 1)),
	consentimiento_at timestamptz NOT NULL,
	creado_at timestamptz NOT NULL DEFAULT now(),
	actualizado_at timestamptz NOT NULL DEFAULT now(),
	FOREIGN KEY (producto_financiamiento_id, producto_id)
		REFERENCES producto_financiamiento(id, producto_id) ON DELETE RESTRICT
);

CREATE TABLE historial_solicitud (
	id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	solicitud_id integer NOT NULL REFERENCES solicitud_financiamiento(id) ON DELETE RESTRICT,
	estado_anterior estado_solicitud,
	estado_nuevo estado_solicitud NOT NULL,
	observacion text,
	usuario_id integer REFERENCES usuario(id) ON DELETE RESTRICT,
	alta smallint NOT NULL DEFAULT 1 CHECK (alta IN (0, 1)),
	creado_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE derivacion_banco (
	id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	solicitud_id integer NOT NULL UNIQUE REFERENCES solicitud_financiamiento(id) ON DELETE RESTRICT,
	codigo_externo varchar(100) UNIQUE,
	derivado_at timestamptz NOT NULL DEFAULT now(),
	estado_respuesta_banco varchar(40) NOT NULL,
	ultima_respuesta_at timestamptz,
	respuesta_detalle jsonb,
	alta smallint NOT NULL DEFAULT 1 CHECK (alta IN (0, 1))
);

CREATE INDEX idx_producto_aliado_estado ON producto (aliado_id, estado);
CREATE INDEX idx_producto_financiamiento_tipo ON producto_financiamiento (producto_id, tipo_financiamiento_id, activo);
CREATE INDEX idx_campana_fechas ON campana (fecha_inicio, fecha_fin);
CREATE INDEX idx_solicitud_cliente ON solicitud_financiamiento (cliente_id, creado_at DESC);
CREATE INDEX idx_solicitud_estado ON solicitud_financiamiento (estado);
CREATE INDEX idx_historial_solicitud_fecha ON historial_solicitud (solicitud_id, creado_at DESC);
