CREATE TABLE public.campana (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(150) NOT NULL,
    descripcion VARCHAR(500),
    fecha_inicio DATE NOT NULL,
    fecha_fin DATE NOT NULL,
    estado VARCHAR(20) NOT NULL DEFAULT 'planificada' CHECK (
        estado IN (
            'planificada',
            'activa',
            'finalizada',
            'cancelada'
        )
    ),
    creado_por_id INTEGER NOT NULL REFERENCES public.usuario (id) ON DELETE RESTRICT,
    alta SMALLINT NOT NULL DEFAULT 1 CHECK (alta IN (0, 1)),
    creado_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    actualizado_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT chk_campana_fechas CHECK (fecha_fin >= fecha_inicio)
);

CREATE INDEX idx_campana_vigencia ON public.campana (fecha_inicio, fecha_fin);
