CREATE TABLE public.regla_precalificacion (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campana_id INTEGER NOT NULL REFERENCES public.campana (id) ON DELETE RESTRICT,
    edad_minima INTEGER NOT NULL CHECK (edad_minima >= 18),
    edad_maxima INTEGER NOT NULL CHECK (edad_maxima >= edad_minima),
    ingreso_minimo NUMERIC(12, 2) NOT NULL CHECK (ingreso_minimo >= 0),
    monto_minimo NUMERIC(12, 2) NOT NULL CHECK (monto_minimo >= 0),
    monto_maximo NUMERIC(12, 2) NOT NULL CHECK (monto_maximo >= monto_minimo),
    plazo_minimo_meses INTEGER NOT NULL CHECK (plazo_minimo_meses > 0),
    plazo_maximo_meses INTEGER NOT NULL CHECK (
        plazo_maximo_meses >= plazo_minimo_meses
    ),
    activo BOOLEAN NOT NULL DEFAULT true,
    alta SMALLINT NOT NULL DEFAULT 1 CHECK (alta IN (0, 1))
);

CREATE INDEX idx_regla_precalificacion_campana ON public.regla_precalificacion (campana_id);
