CREATE TABLE public.lista_interes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id INTEGER NOT NULL REFERENCES public.cliente (id) ON DELETE RESTRICT,
    producto_id INTEGER NOT NULL REFERENCES public.producto (id) ON DELETE RESTRICT,
    creado_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    alta SMALLINT NOT NULL DEFAULT 1 CHECK (alta IN (0, 1)),
    CONSTRAINT uq_lista_interes_cliente_producto UNIQUE (cliente_id, producto_id)
);

CREATE INDEX idx_lista_interes_producto ON public.lista_interes (producto_id);
