CREATE TABLE public.solicitud_financiamiento (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id INTEGER NOT NULL REFERENCES public.cliente (id) ON DELETE RESTRICT,
    producto_id INTEGER NOT NULL REFERENCES public.producto (id) ON DELETE RESTRICT,
    producto_financiamiento_id INTEGER NOT NULL,
    campana_id INTEGER REFERENCES public.campana (id) ON DELETE RESTRICT,
    monto_solicitado NUMERIC(12, 2) NOT NULL CHECK (monto_solicitado >= 0),
    moneda VARCHAR(3) NOT NULL DEFAULT 'PEN',
    plazo_meses INTEGER NOT NULL CHECK (plazo_meses > 0),
    tasa_tipo_aplicada tipo_tasa_interes NOT NULL,
    tasa_anual_aplicada NUMERIC(5, 2) NOT NULL CHECK (
        tasa_anual_aplicada >= 0
        AND tasa_anual_aplicada <= 100
    ),
    resultado_precalificacion resultado_precalificacion NOT NULL DEFAULT 'pendiente',
    estado estado_solicitud NOT NULL DEFAULT 'precalificado',
    consentimiento_at TIMESTAMPTZ NOT NULL,
    alta SMALLINT NOT NULL DEFAULT 1 CHECK (alta IN (0, 1)),
    creado_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    actualizado_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_solicitud_producto_financiamiento FOREIGN KEY (
        producto_financiamiento_id,
        producto_id
    ) REFERENCES public.producto_financiamiento (id, producto_id) ON DELETE RESTRICT
);

CREATE INDEX idx_solicitud_cliente ON public.solicitud_financiamiento (cliente_id);

CREATE INDEX idx_solicitud_estado ON public.solicitud_financiamiento (estado);

CREATE INDEX idx_solicitud_creado_at ON public.solicitud_financiamiento (creado_at);
