CREATE TABLE public.historial_solicitud (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    solicitud_id INTEGER NOT NULL REFERENCES public.solicitud_financiamiento (id) ON DELETE RESTRICT,
    estado_anterior estado_solicitud,
    estado_nuevo estado_solicitud NOT NULL,
    observacion VARCHAR(500),
    usuario_id INTEGER NOT NULL REFERENCES public.usuario (id) ON DELETE RESTRICT,
    creado_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    alta SMALLINT NOT NULL DEFAULT 1 CHECK (alta IN (0, 1))
);

CREATE INDEX idx_historial_solicitud_solicitud ON public.historial_solicitud (solicitud_id);
