CREATE TABLE public.derivacion_banco (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    solicitud_id INTEGER NOT NULL UNIQUE REFERENCES public.solicitud_financiamiento (id) ON DELETE RESTRICT,
    codigo_externo VARCHAR(50) UNIQUE,
    derivado_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    estado_respuesta_banco VARCHAR(20) NOT NULL DEFAULT 'pendiente' CHECK (
        estado_respuesta_banco IN (
            'pendiente',
            'aprobado',
            'rechazado',
            'error'
        )
    ),
    ultima_respuesta_at TIMESTAMPTZ,
    respuesta_detalle TEXT,
    alta SMALLINT NOT NULL DEFAULT 1 CHECK (alta IN (0, 1))
);
