CREATE TABLE public.aliado (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_documento tipo_documento NOT NULL DEFAULT 'RUC' CHECK (tipo_documento = 'RUC'),
    numero_documento VARCHAR(11) NOT NULL UNIQUE CHECK (
        numero_documento ~ '^[0-9]{11}$'
    ),
    razon_social VARCHAR(150) NOT NULL,
    contacto_nombre VARCHAR(150),
    contacto_correo CITEXT,
    contacto_telefono VARCHAR(20),
    estado VARCHAR(20) NOT NULL DEFAULT 'activo' CHECK (
        estado IN ('activo', 'inactivo')
    ),
    alta SMALLINT NOT NULL DEFAULT 1 CHECK (alta IN (0, 1)),
    creado_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    actualizado_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
