CREATE TABLE public.cliente (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_persona tipo_persona NOT NULL,
    tipo_documento tipo_documento NOT NULL,
    numero_documento VARCHAR(11) NOT NULL,
    nombres VARCHAR(100),
    apellidos VARCHAR(100),
    razon_social VARCHAR(150),
    correo CITEXT,
    telefono VARCHAR(20),
    alta SMALLINT NOT NULL DEFAULT 1 CHECK (alta IN (0, 1)),
    creado_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    actualizado_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_cliente_documento UNIQUE (
        tipo_documento,
        numero_documento
    ),
    CONSTRAINT chk_cliente_persona CHECK (
        (
            tipo_persona = 'NATURAL'
            AND tipo_documento IN ('DNI', 'CE', 'PASAPORTE')
            AND nombres IS NOT NULL
            AND apellidos IS NOT NULL
            AND razon_social IS NULL
        )
        OR (
            tipo_persona = 'JURIDICA'
            AND tipo_documento = 'RUC'
            AND numero_documento ~ '^[0-9]{11}$'
            AND razon_social IS NOT NULL
            AND nombres IS NULL
            AND apellidos IS NULL
        )
    )
);
