CREATE TABLE public.producto (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aliado_id INTEGER NOT NULL REFERENCES public.aliado (id) ON DELETE RESTRICT,
    categoria_id INTEGER REFERENCES public.categoria (id) ON DELETE RESTRICT,
    nombre VARCHAR(150) NOT NULL,
    descripcion VARCHAR(500),
    precio_lista NUMERIC(12, 2) NOT NULL CHECK (precio_lista >= 0),
    moneda VARCHAR(3) NOT NULL DEFAULT 'PEN',
    incluye_igv BOOLEAN NOT NULL DEFAULT true,
    imagen_url VARCHAR(500),
    estado VARCHAR(20) NOT NULL DEFAULT 'activo' CHECK (
        estado IN ('activo', 'inactivo')
    ),
    alta SMALLINT NOT NULL DEFAULT 1 CHECK (alta IN (0, 1)),
    creado_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    actualizado_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_producto_aliado ON public.producto (aliado_id);

CREATE INDEX idx_producto_estado ON public.producto (estado);
