CREATE TABLE public.producto_financiamiento (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    producto_id INTEGER NOT NULL REFERENCES public.producto (id) ON DELETE RESTRICT,
    tipo_financiamiento_id INTEGER NOT NULL REFERENCES public.tipo_financiamiento (id) ON DELETE RESTRICT,
    tipo_tasa tipo_tasa_interes NOT NULL,
    tasa_anual NUMERIC(5, 2) NOT NULL CHECK (
        tasa_anual >= 0
        AND tasa_anual <= 100
    ),
    plazo_minimo_meses INTEGER NOT NULL CHECK (plazo_minimo_meses > 0),
    plazo_maximo_meses INTEGER NOT NULL CHECK (plazo_maximo_meses > 0),
    monto_minimo NUMERIC(12, 2) NOT NULL CHECK (monto_minimo >= 0),
    monto_maximo NUMERIC(12, 2) NOT NULL CHECK (monto_maximo >= 0),
    vigente_desde DATE NOT NULL,
    vigente_hasta DATE,
    activo BOOLEAN NOT NULL DEFAULT true,
    alta SMALLINT NOT NULL DEFAULT 1 CHECK (alta IN (0, 1)),
    -- soporta la FK compuesta (id, producto_id) referenciada desde solicitud_financiamiento
    CONSTRAINT uq_producto_financiamiento_producto UNIQUE (id, producto_id),
    CONSTRAINT chk_producto_financiamiento_plazo CHECK (
        plazo_maximo_meses >= plazo_minimo_meses
    ),
    CONSTRAINT chk_producto_financiamiento_monto CHECK (monto_maximo >= monto_minimo),
    CONSTRAINT chk_producto_financiamiento_vigencia CHECK (
        vigente_hasta IS NULL
        OR vigente_hasta >= vigente_desde
    )
);

CREATE INDEX idx_producto_financiamiento_producto ON public.producto_financiamiento (producto_id);

CREATE INDEX idx_producto_financiamiento_tipo ON public.producto_financiamiento (tipo_financiamiento_id);
