CREATE TABLE public.usuario (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rol_id INTEGER NOT NULL REFERENCES public.rol (id) ON DELETE RESTRICT,
    aliado_id INTEGER REFERENCES public.aliado (id) ON DELETE RESTRICT,
    correo_electronico CITEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT true,
    ultimo_acceso_at TIMESTAMPTZ,
    alta SMALLINT NOT NULL DEFAULT 1 CHECK (alta IN (0, 1)),
    creado_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    actualizado_at TIMESTAMPTZ NOT NULL DEFAULT now()
    -- regla "aliado requiere aliado_id / administrador no lo requiere" se valida en backend por depender del nombre_rol
);

CREATE INDEX idx_usuario_rol ON public.usuario (rol_id);

CREATE INDEX idx_usuario_aliado ON public.usuario (aliado_id);
